name: splitwise
description: A new Flutter project.

publish_to: 'none'   

version: 1.0.0+4

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  contacts_service: ^0.6.3
  app_settings: ^4.2.0

  #For Select the Currency with Currency code
  currency_picker: ^2.0.16

  #For Format the Date
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/Fonts/NotoSerifKhojki-Regular.ttf


    
    
    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
